---
- name: >-
    18.10.26.1.1 | L1 |
    Ensure 'Application: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled'
  when:
    - w2025cis_rule_18_10_26_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application
    name: Retention
    data: 0
    type: string
    state: present

- name: >-
    18.10.26.1.2 | L1 |
    Ensure 'Application: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'
  when:
    - w2025cis_rule_18_10_26_1_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Application
    name: MaxSize
    data: "{{ w2025cis_application_log_max_size_in_kb }}"
    type: dword
    state: present

- name: >-
    18.10.26.2.1 | L1 |
    Ensure 'Security: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled'
  when:
    - w2025cis_rule_18_10_26_2_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security
    name: Retention
    data: 0
    type: string
    state: present

- name: >-
    18.10.26.2.2 | L1 |
    Ensure 'Security: Specify the maximum log file size (KB)' is set to 'Enabled: 196,608 or greater'
  when:
    - w2025cis_rule_18_10_26_2_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Security
    name: MaxSize
    data: "{{ w2025cis_security_log_max_size_in_kb }}"
    type: dword
    state: present

- name: >-
    18.10.26.3.1 | L1 |
    Ensure 'Setup: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled'
  when:
    - w2025cis_rule_18_10_26_3_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup
    name: Retention
    data: 0
    type: string
    state: present

- name: >-
    18.10.26.3.2 | L1 |
    Ensure 'Setup: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'
  when:
    - w2025cis_rule_18_10_26_3_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\Setup
    name: MaxSize
    data: "{{ w2025cis_setup_log_max_size_in_kb }}"
    type: dword
    state: present

- name: >-
    18.10.26.4.1 | L1 |
    Ensure 'System: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled'
  when:
    - w2025cis_rule_18_10_26_4_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\System
    name: Retention
    data: 0
    type: string
    state: present

- name: >-
    18.10.26.4.2 | L1 | Ensure 'System: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater'
  when:
    - w2025cis_rule_18_10_26_4_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\EventLog\System
    name: MaxSize
    data: "{{ w2025cis_system_log_max_size_in_kb }}"
    type: dword
    state: present
