---
- name: "18.10.81.1 | L2 | Ensure 'Allow suggested apps in Windows Ink Workspace' is set to 'Disabled'"
  when:
    - w2025cis_rule_18_10_81_1_enabled
    - w2025cis_rule_18_10_81_1_force or _w2025cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace
    name: AllowSuggestedAppsInWindowsInkWorkspace
    data: 0
    type: dword
    state: present

- name: >-
    18.10.81.2 | L1 |
    Ensure 'Allow Windows Ink Workspace' is set to 'Enabled: On, but disallow access above lock' OR 'Enabled: Disabled'
  when:
    - w2025cis_rule_18_10_81_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace
    name: AllowWindowsInkWorkspace
    data: "{{ _w2025cis_windows_ink_workspace_access_value }}"
    type: dword
    state: present
