---
- name: "18.5.1 | L1 | Ensure 'MSS: (AutoAdminLogon) Enable Automatic Logon' is set to 'Disabled'"
  when:
    - w2019cis_rule_18_5_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 0
    type: string
    state: present

- name: >-
    18.5.2 | L1 |
    Ensure 'MSS: (DisableIPSourceRouting IPv6) IP source routing protection level'
    is set to 'Enabled: Highest protection, source routing is completely disabled'
  when:
    - w2019cis_rule_18_5_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
    name: DisableIPSourceRouting
    data: 2
    type: dword
    state: present

- name: >-
    18.5.3 | L1 |
    Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level'
    is set to 'Enabled: Highest protection, source routing is completely disabled'
  when:
    - w2019cis_rule_18_5_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: DisableIPSourceRouting
    data: 2
    type: dword
    state: present

- name: >-
    18.5.4 | L1 |
    Ensure 'MSS: (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes' is set to 'Disabled'
  when:
    - w2019cis_rule_18_5_4_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: EnableICMPRedirect
    data: 0
    type: dword
    state: present

- name: >-
    18.5.5 | L2 |
    Ensure 'MSS: (KeepAliveTime) How often keep-alive packets are sent in milliseconds'
    is set to 'Enabled: 300,000 or 5 minutes'
  when:
    - w2019cis_rule_18_5_5_enabled
    - w2019cis_rule_18_5_5_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: KeepAliveTime
    data: 300000
    type: dword
    state: present

- name: >-
    18.5.6 | L1 |
    Ensure 'MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS
    servers' is set to 'Enabled'
  when:
    - w2019cis_rule_18_5_6_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters
    name: NoNameReleaseOnDemand
    data: 1
    type: dword
    state: present

- name: >-
    18.5.7 | L2 |
    Ensure 'MSS: (PerformRouterDiscovery) Allow IRDP to detect and configure Default Gateway addresses'
    is set to 'Disabled'
  when:
    - w2019cis_rule_18_5_7_enabled
    - w2019cis_rule_18_5_7_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: PerformRouterDiscovery
    data: 0
    type: dword
    state: present

- name: "18.5.8 | L1 | Ensure 'MSS: (SafeDllSearchMode) Enable Safe DLL search mode' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_5_8_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
    name: SafeDllSearchMode
    data: 1
    type: dword
    state: present

- name: >-
    18.5.9 | L1 |
    Ensure 'MSS: (ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires'
    is set to 'Enabled: 5 or fewer seconds'
  when:
    - w2019cis_rule_18_5_9_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: ScreenSaverGracePeriod
    data: "{{ w2019cis_screensaver_grace_period_in_seconds }}"
    type: string
    state: present

- name: >-
    18.5.10 | L2 |
    Ensure 'MSS: (TcpMaxDataRetransmissions IPv6) How many times unacknowledged data is retransmitted'
    is set to 'Enabled: 3'
  when:
    - w2019cis_rule_18_5_10_enabled
    - w2019cis_rule_18_5_10_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\TCPIP6\Parameters
    name: TcpMaxDataRetransmissions
    data: 3
    type: dword
    state: present

- name: >-
    18.5.11 | L2 |
    Ensure 'MSS: (TcpMaxDataRetransmissions) How many times unacknowledged data is retransmitted' is set to 'Enabled: 3'
  when:
    - w2019cis_rule_18_5_11_enabled
    - w2019cis_rule_18_5_11_force or _w2019cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
    name: TcpMaxDataRetransmissions
    data: 3
    type: dword
    state: present

- name: >-
    18.5.12 | L1 |
    Ensure 'MSS: (WarningLevel) Percentage threshold for the security event log at which the system will generate a
    warning' is set to 'Enabled: 90% or less'
  when:
    - w2019cis_rule_18_5_12_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\Eventlog\Security
    name: WarningLevel
    data: "{{ w2019cis_security_log_warning_level }}"
    type: dword
    state: present
