---
- name: "18.10.42.4.1 | L1 | Ensure 'Enable EDR in block mode' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_4_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Features
    name: PassiveRemediation
    data: 1
    type: dword
    state: present

- name: >-
    18.10.42.5.1 | L1 | Ensure 'Configure local setting override for reporting to Microsoft MAPS' is set to 'Disabled'
  when:
    - w2022cis_rule_18_10_42_5_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet
    name: LocalSettingOverrideSpynetReporting
    data: 0
    type: dword
    state: present

- name: "18.10.42.5.2 | L1 | Ensure 'Join Microsoft MAPS' is set to 'Enabled: Advanced'"
  when:
    - w2022cis_rule_18_10_42_5_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet
    name: SpynetReporting
    data: 2
    type: dword
    state: present

- name: "18.10.42.6.1.1 | L1 | Ensure 'Configure Attack Surface Reduction rules' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_6_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR
    name: ExploitGuard_ASR_Rules
    data: 1
    type: dword
    state: present

- name: >-
    18.10.42.6.1.2 | L1 |
    Ensure 'Configure Attack Surface Reduction rules: Set the state for each ASR rule' is configured
  loop:
    - 26190899-1602-49e8-8b27-eb1d0a1ce869
    - 3b576869-a4ec-4529-8536-b80a7769e899
    - 56a863a9-875e-4185-98a7-b882c64b5ce5
    - 5beb7efe-fd9a-4556-801d-275e5ffc04cc
    - 75668c1f-73b5-4cf0-bb93-3ecf5cb7cc84
    - 7674ba52-37eb-4a4f-a9a1-f0f9a1619a2c
    - 9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2
    - b2b3f03d-6a65-4f7b-a9c7-1c7ef74a9ba4
    - be9ba2d9-53ea-4cdc-84e5-9b1eeee46550
    - d3e037e1-3eb8-44c8-a917-57927947596d
    - d4f940ab-401b-4efc-aadc-ad5f3c50688a
    - e6db77e5-3df2-4cf1-b95a-636979351e5b
  when:
    - w2022cis_rule_18_10_42_6_1_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\ASR\Rules
    name: "{{ item }}"
    data: 1
    type: string
    state: present

- name: >-
    18.10.42.6.3.1 | L1 | Ensure 'Prevent users and apps from accessing dangerous websites' is set to 'Enabled: Block'
  when:
    - w2022cis_rule_18_10_42_6_3_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Windows Defender Exploit Guard\Network Protection
    name: EnableNetworkProtection
    data: 1
    type: dword
    state: present

- name: "18.10.42.7.1 | L2 | Ensure 'Enable file hash computation feature' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_7_1_enabled
    - w2022cis_rule_18_10_42_7_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\MpEngine
    name: EnableFileHashComputation
    data: 1
    type: dword
    state: present

- name: "18.10.42.8.1 | L2 | Ensure 'Convert warn verdict to block' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_8_1_enabled
    - w2022cis_rule_18_10_42_8_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\NIS
    name: EnableConvertWarnToBlock
    data: 1
    type: dword
    state: present

- name: >-
    18.10.42.10.1 | L1 |
    Ensure 'Configure real-time protection and Security Intelligence Updates during OOBE' is set to 'Enabled'
  when:
    - w2022cis_rule_18_10_42_10_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: OobeEnableRtpAndSigUpdate
    data: 1
    type: dword
    state: present

- name: "18.10.42.10.2 | L1 | Ensure 'Scan all downloaded files and attachments' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_10_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableIOAVProtection
    data: 0
    type: dword
    state: present

- name: "18.10.42.10.3 | L1 | Ensure 'Turn off real-time protection' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_42_10_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableRealtimeMonitoring
    data: 0
    type: dword
    state: present

- name: "18.10.42.10.4 | L1 | Ensure 'Turn on behavior monitoring' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_10_4_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableBehaviorMonitoring
    data: 0
    type: dword
    state: present

- name: "18.10.42.10.5 | L1 | Ensure 'Turn on script scanning' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_10_5_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection
    name: DisableScriptScanning
    data: 0
    type: dword
    state: present

- name: >-
    18.10.42.11.1.1.1 | L2 |
    Ensure 'Configure Brute-Force Protection aggressiveness' is set to 'Enabled: Medium' or higher
  when:
    - w2022cis_rule_18_10_42_11_1_1_1_enabled
    - w2022cis_rule_18_10_42_11_1_1_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Remediation\Behavioral Network Blocks\Brute Force Protection
    name: BruteForceProtectionAggressiveness
    data: "{{ _w2022cis_brute_force_protection_aggressiveness_value }}"
    type: dword
    state: present

- name: >-
    18.10.42.11.1.1.2 | L1 | Ensure 'Configure Remote Encryption Protection Mode' is set to 'Enabled: Audit' or higher
  when:
    - w2022cis_rule_18_10_42_11_1_1_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Remediation\Behavioral Network Blocks\Brute Force Protection
    name: BruteForceProtectionConfiguredState
    data: "{{ _w2022cis_brute_force_protection_configured_state_value }}"
    type: dword
    state: present

- name: >-
    18.10.42.11.1.2.1 | L2 |
    Ensure 'Configure how aggressively Remote Encryption Protection blocks threats'
    is set to 'Enabled: Medium' or higher
  when:
    - w2022cis_rule_18_10_42_11_1_2_1_enabled
    - w2022cis_rule_18_10_42_11_1_2_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Remediation\Behavioral Network Blocks\Remote Encryption Protection
    name: RemoteEncryptionProtectionAggressiveness
    data: "{{ _w2022cis_remote_encryption_protection_aggressiveness_value }}"
    type: dword
    state: present

- name: "18.10.42.12.1 | L2 | Ensure 'Configure Watson events' is set to 'Disabled'"
  when:
    - w2022cis_rule_18_10_42_12_1_enabled
    - w2022cis_rule_18_10_42_12_1_force or _w2022cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Reporting
    name: DisableGenericRePorts
    data: 1
    type: dword
    state: present

- name: "18.10.42.13.1 | L1 | Ensure 'Scan excluded files and directories during quick scans' is set to 'Enabled: 1'"
  when:
    - w2022cis_rule_18_10_42_13_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: QuickScanIncludeExclusions
    data: 1
    type: dword
    state: present

- name: "18.10.42.13.2 | L1 | Ensure 'Scan packed executables' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_13_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DisablePackedExeScanning
    data: 0
    type: dword
    state: present

- name: "18.10.42.13.3 | L1 | Ensure 'Scan removable drives' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_13_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DisableRemovableDriveScanning
    data: 0
    type: dword
    state: present

- name: "18.10.42.13.4 | L1 | Ensure 'Trigger a quick scan after X days without any scans' is set to 'Enabled: 7'"
  when:
    - w2022cis_rule_18_10_42_13_4_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DaysUntilAggressiveCatchupQuickScan
    data: 7
    type: dword
    state: present

- name: "18.10.42.13.5 | L1 | Ensure 'Turn on e-mail scanning' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_13_5_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender\Scan
    name: DisableEmailScanning
    data: 0
    type: dword
    state: present

- name: >-
    18.10.42.16 | L1 | Ensure 'Configure detection for potentially unwanted applications' is set to 'Enabled: Block'
  when:
    - w2022cis_rule_18_10_42_16_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Defender
    name: PUAProtection
    data: 1
    type: dword
    state: present

- name: "18.10.42.17 | L1 | Ensure 'Control whether exclusions are visible to local users' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_10_42_17_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender
    name: HideExclusionsFromLocalUsers
    data: 1
    type: dword
    state: present
