---
- name: >-
    18.10.83.1 | L1 |
    Ensure 'Configure the transmission of the user's password in the content of MPR notifications sent by winlogon.'
    is set to 'Disabled'
  when:
    - w2022cis_rule_18_10_83_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
    name: EnableMPR
    data: 0
    type: dword

- name: >-
    18.10.83.2 | L1 | Ensure 'Sign-in and lock last interactive user automatically after a restart' is set to 'Disabled'
  when:
    - w2022cis_rule_18_10_83_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\System
    name: DisableAutomaticRestartSignOn
    data: 1
    type: dword
