---
- name: "18.9.27.1 | L1 | Ensure 'Allow Custom SSPs and APs to be loaded into LSASS' is set to 'Disabled'"
  when:
    - w2025cis_rule_18_9_27_1_enabled
    - _w2025cis_domain_controller
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: AllowCustomSSPsAPs
    data: 0
    type: dword

- name: >-
    18.9.27.2 | NG | Ensure 'Configures LSASS to run as a protected process' is set to 'Enabled: Enabled with UEFI Lock'
  when:
    - w2025cis_rule_18_9_27_2_enabled
    - w2025cis_rule_18_9_27_2_force or _w2025cis_ngws
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    name: RunAsPPL
    data: 1
    type: dword
