---
- name: "18.9.38.1 | L1 | Ensure 'Enable RPC Endpoint Mapper Client Authentication' is set to 'Enabled' | MS only"
  when:
    - w2025cis_rule_18_9_38_1_enabled
    - _w2025cis_standalone_or_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
    name: EnableAuthEpResolution
    data: 1
    type: dword
    state: present
  notify:
    - _w2025cis_reboot_windows

- name: "18.9.38.2 | L2 | Ensure 'Restrict Unauthenticated RPC clients' is set to 'Enabled: Authenticated' | MS only"
  when:
    - w2025cis_rule_18_9_38_2_enabled
    - _w2025cis_standalone_or_member_server
    - w2025cis_rule_18_9_38_2_force or _w2025cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows Nt\Rpc
    name: RestrictRemoteClients
    data: 1
    type: dword
    state: present
  notify:
    - _w2025cis_reboot_windows
