---
- name: 5.2.1 | Ensure sudo is installed
  when:
    - rhel8cis_rule_5_2_1_enabled
  become: true
  ansible.builtin.dnf:
    name:
      - sudo
    state: present

- name: 5.2.2 | Ensure sudo commands use pty
  when:
    - rhel8cis_rule_5_2_2_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: 'Defaults use_pty'
    insertbefore: '^#includedir /etc/sudoers.d'

- name: 5.2.3 | Ensure sudo log file exists
  when:
    - rhel8cis_rule_5_2_3_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults\s+logfile='
    line: 'Defaults logfile={{ rhel8cis_sudo_log_file }}'
    insertbefore: '^#includedir /etc/sudoers.d'

- name: 5.2 | Configure privilege escalation | Get /etc/sudoers.d/* files
  when:
    - (rhel8cis_rule_5_2_4_enabled and
      (rhel8cis_rule_5_2_4_force or _rhel8cis_level2)) or
      rhel8cis_rule_5_2_5_enabled
  become: true
  ansible.builtin.find:
    paths:
      - /etc/sudoers.d
    file_type: file
    recurse: true
  register: _rhel8cis_sudoers_d_files

- name: 5.2.4 | Ensure users must provide password for escalation
  when:
    - rhel8cis_rule_5_2_4_enabled
    - rhel8cis_rule_5_2_4_force or _rhel8cis_level2
  become: true
  block:
    - name: 5.2.4 | Ensure users must provide password for escalation | /etc/sudoers
      ansible.builtin.replace:
        path: /etc/sudoers
        regexp: '^([^#|].*)NOPASSWD(.*)'
        replace: '\1PASSWD\2'

    - name: 5.2.4 | Ensure users must provide password for escalation | /etc/sudoers.d/*
      loop: "{{ _rhel8cis_sudoers_d_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^([^#|].*)NOPASSWD(.*)'
        replace: '\1PASSWD\2'

- name: 5.2.5 | Ensure re-authentication for privilege escalation is not disabled globally
  when:
    - rhel8cis_rule_5_2_5_enabled
  become: true
  block:
    - name: 5.2.5 | Ensure re-authentication for privilege escalation is not disabled globally | /etc/sudoers
      ansible.builtin.replace:
        path: /etc/sudoers
        regexp: '^([^#].*)!authenticate(.*)'
        replace: '\1authenticate\2'

    - name: 5.2.5 | Ensure re-authentication for privilege escalation is not disabled globally | /etc/sudoers.d/*
      loop: "{{ _rhel8cis_sudoers_d_files.files }}"
      loop_control:
        label: "{{ item.path }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^([^#].*)!authenticate(.*)'
        replace: '\1authenticate\2'

- name: 5.2.6 | Ensure sudo timestamp_timeout is configured
  when:
    - rhel8cis_rule_5_2_6_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^#?Defaults\s+timestamp_timeout='
    line: 'Defaults timestamp_timeout={{ rhel8cis_sudo_authentication_timeout }}'
    insertbefore: '^#includedir /etc/sudoers.d'

- name: 5.2.7 | Ensure access to the su command is restricted
  when:
    - rhel8cis_rule_5_2_7_enabled
  become: true
  block:
    - name: 5.2.7 | Ensure access to the su command is restricted | Create group
      ansible.builtin.group:
        name: "{{ rhel8cis_su_group_name }}"
        system: true
        state: present

    - name: 5.2.7 | Ensure access to the su command is restricted | Set group membership
      ansible.builtin.lineinfile:
        path: /etc/group
        regexp: '^{{ rhel8cis_su_group_name }}(:.:.*:).*$'
        line: '{{ rhel8cis_su_group_name }}\1{{ rhel8cis_su_group_members | join(",") }}'
        backrefs: true

    - name: 5.2.7 | Ensure access to the su command is restricted | /etc/pam.d/su
      ansible.builtin.lineinfile:
        path: /etc/pam.d/su
        regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
        line: "auth required pam_wheel.so use_uid group={{ rhel8cis_su_group_name }}"
