---
- name: "19.5.1.1 | L1 | Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled'"
  loop: "{{ _w2019cis_user_hives.sub_keys }}"
  when:
    - w2019cis_rule_19_5_1_1_enabled
    - "'Classes' not in item"
  ansible.windows.win_regedit:
    path: "HKU:\\{{ item }}\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\PushNotifications"
    name: NoToastApplicationNotificationOnLockScreen
    data: 1
    type: dword
    state: present
