---
- name: >-
    2.3.15.1 | L1 | Ensure 'System objects: Require case insensitivity for non-Windows subsystems' is set to 'Enabled'
  when:
    - w11cis_rule_2_3_15_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Kernel
    name: ObCaseInsensitive
    data: 1
    type: dword
    state: present

- name: >-
    2.3.15.2 | L1 |
    Ensure 'System objects: Strengthen default permissions of internal system objects (e.g. Symbolic Links)'
    is set to 'Enabled'
  when:
    - w11cis_rule_2_3_15_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager
    name: ProtectionMode
    data: 1
    type: dword
    state: present
