---
- name: "18.9.31.1.1 | L1 | Ensure 'Block NetBIOS-based discovery for domain controller location' is set to 'Enabled'"
  when:
    - w11cis_rule_18_9_31_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Netlogon\Parameters
    name: BlockNetbiosDiscovery
    data: 1
    type: dword
    state: present
