---
- name: 1.5.1 | Ensure core file size is configured
  when:
    - rhel8cis_rule_1_5_1_enabled
  become: true
  community.general.pam_limits:
    domain: '*'
    limit_type: hard
    limit_item: core
    value: '0'

- name: 1.5.2 | Ensure fs.protected_hardlinks is configured
  when:
    - rhel8cis_rule_1_5_2_enabled
  become: true
  ansible.posix.sysctl:
    name: fs.protected_hardlinks
    value: '1'
    state: present
    sysctl_set: true

- name: 1.5.3 | Ensure fs.protected_symlinks is configured
  when:
    - rhel8cis_rule_1_5_3_enabled
    - rhel8cis_rule_1_5_3_force or _rhel8cis_level2
  become: true
  ansible.posix.sysctl:
    name: fs.protected_symlinks
    value: '1'
    state: present
    sysctl_set: true

- name: 1.5.4 | Ensure fs.suid_dumpable is configured
  when:
    - rhel8cis_rule_1_5_4_enabled
  become: true
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '0'
    state: present
    sysctl_set: true

- name: 1.5.5 | Ensure kernel.dmesg_restrict is configured
  when:
    - rhel8cis_rule_1_5_5_enabled
  become: true
  ansible.posix.sysctl:
    name: kernel.dmesg_restrict
    value: '1'
    state: present
    sysctl_set: true

- name: 1.5.6 | Ensure kernel.kptr_restrict is configured
  when:
    - rhel8cis_rule_1_5_6_enabled
  become: true
  ansible.posix.sysctl:
    name: kernel.kptr_restrict
    value: "{{ _rhel8cis_kptr_restrict_value }}"
    state: present
    sysctl_set: true

- name: 1.5.7 | Ensure kernel.yama.ptrace_scope is configured
  when:
    - rhel8cis_rule_1_5_7_enabled
  become: true
  ansible.posix.sysctl:
    name: kernel.yama.ptrace_scope
    value: "{{ _rhel8cis_ptrace_scope_value }}"
    state: present
    sysctl_set: true

- name: 1.5.8 | Ensure kernel.randomize_va_space is configured
  when:
    - rhel8cis_rule_1_5_8_enabled
  become: true
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: '2'
    state: present
    sysctl_set: true

- name: 1.5.9 | Ensure systemd-coredump ProcessSizeMax is configured
  when:
    - rhel8cis_rule_1_5_9_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^#?\s*ProcessSizeMax='
    line: 'ProcessSizeMax=0'

- name: 1.5.10 | Ensure systemd-coredump Storage is configured
  when:
    - rhel8cis_rule_1_5_10_enabled
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/coredump.conf
    regexp: '^#?\s*Storage='
    line: 'Storage=none'
