---
- name: 1.7.1 | Ensure /etc/motd is configured
  when:
    - rhel8cis_rule_1_7_1_enabled
  become: true
  block:
    - name: 1.7.1 | Ensure /etc/motd is configured | Set content # noqa risky-file-permissions
      when:
        - rhel8cis_use_motd
      ansible.builtin.copy:
        content: "{{ rhel8cis_motd_banner }}"
        dest: /etc/motd

    - name: 1.7.1 | Ensure /etc/motd is configured | Remove content # noqa risky-file-permissions
      when:
        - not rhel8cis_use_motd
      ansible.builtin.copy:
        content: ''
        dest: /etc/motd

- name: 1.7.2 | Ensure /etc/issue is configured
  when:
    - rhel8cis_rule_1_7_2_enabled
  become: true
  block:
    - name: 1.7.2 | Ensure /etc/issue is configured | Set content # noqa risky-file-permissions
      when:
        - rhel8cis_use_issue
      ansible.builtin.copy:
        content: "{{ rhel8cis_issue_banner }}"
        dest: /etc/issue

    - name: 1.7.2 | Ensure /etc/issue is configured | Remove content # noqa risky-file-permissions
      when:
        - not rhel8cis_use_issue
      ansible.builtin.copy:
        content: ''
        dest: /etc/issue

- name: 1.7.3 | Ensure /etc/issue.net is configured
  when:
    - rhel8cis_rule_1_7_3_enabled
  become: true
  block:
    - name: 1.7.3 | Ensure /etc/issue.net is configured | Set content # noqa risky-file-permissions
      when:
        - rhel8cis_use_issue_net
      ansible.builtin.copy:
        content: "{{ rhel8cis_issue_net_banner }}"
        dest: /etc/issue.net

    - name: 1.7.3 | Ensure /etc/issue.net is configured | Remove content # noqa risky-file-permissions
      when:
        - not rhel8cis_use_issue_net
      ansible.builtin.copy:
        content: ''
        dest: /etc/issue.net

- name: 1.7.4 | Ensure access to /etc/motd is configured
  when:
    - rhel8cis_rule_1_7_4_enabled
  become: true
  ansible.builtin.file:
    path: /etc/motd
    owner: root
    group: root
    mode: '0644'
    state: file

- name: 1.7.5 | Ensure access to /etc/issue is configured
  when:
    - rhel8cis_rule_1_7_5_enabled
  become: true
  ansible.builtin.file:
    path: /etc/issue
    owner: root
    group: root
    mode: '0644'
    state: file

- name: 1.7.6 | Ensure access to /etc/issue.net is configured
  when:
    - rhel8cis_rule_1_7_6_enabled
  become: true
  ansible.builtin.file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
    state: file
