---
- name: "18.9.53.1.1 | L1 | Ensure 'Enable Windows NTP Client' is set to 'Enabled'"
  when:
    - w2022cis_rule_18_9_53_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpclient
    name: Enabled
    data: 1
    type: dword

- name: "18.9.53.1.2 | L1 | Ensure 'Enable Windows NTP Server' is set to 'Disabled' | MS only"
  when:
    - w2022cis_rule_18_9_53_1_2_enabled
    - _w2022cis_standalone_or_member_server
  ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32Time\Timeproviders\Ntpserver
    name: Enabled
    data: 1
    type: dword
