---
- name: "18.10.50.1 | L2 | Ensure 'Prevent the usage of OneDrive for file storage' is set to 'Enabled'"
  when:
    - w11cis_rule_18_10_50_1_enabled
    - w11cis_rule_18_10_50_1_force or _w11cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\OneDrive
    name: DisableFileSyncNGSC
    data: 1
    type: dword
    state: present
