---
- name: "18.10.88.1 | L2 | Ensure 'Turn on PowerShell Script Block Logging' is set to 'Enabled'"
  when:
    - w11cis_rule_18_10_88_1_enabled
    - w11cis_rule_18_10_88_1_force or _w11cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
    name: EnableScriptBlockLogging
    data: 1
    type: dword
    state: present

- name: "18.10.88.2 | L2 | Ensure 'Turn on PowerShell Transcription' is set to 'Enabled'"
  when:
    - w11cis_rule_18_10_88_2_enabled
    - w11cis_rule_18_10_88_2_force or _w11cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription
    name: EnableTranscripting
    data: 1
    type: dword
    state: present
