---
- name: "18.10.4.1 | L2 | Ensure 'Allow a Windows app to share application data between users' is set to 'Disabled'"
  when:
    - w11cis_rule_18_10_4_1_enabled
    - w11cis_rule_18_10_4_1_force or _w11cis_level2
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\AppModel\StateManager
    name: AllowSharedLocalAppData
    data: 0
    type: dword
    state: present

- name: >-
    18.10.4.2 | L1 |
    Ensure 'Not allow per-user unsigned packages to install by default (requires explicitly allow per install)'
    is set to 'Enabled'
  when:
    - w11cis_rule_18_10_4_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Appx
    name: DisablePerUserUnsignedPackagesByDefault
    data: 1
    type: dword
    state: present

- name: "18.10.4.3 | L1 | Ensure 'Prevent non-admin users from installing packaged Windows apps' is set to 'Enabled'"
  when:
    - w11cis_rule_18_10_4_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Appx
    name: BlockNonAdminUserInstall
    data: 1
    type: dword
    state: present
