---
- name: "18.10.8.1 | L1 | Ensure 'Disallow Autoplay for non-volume devices' is set to 'Enabled'"
  when:
    - w11cis_rule_18_10_8_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Explorer
    name: NoAutoplayforNonVolume
    data: 1
    type: dword
    state: present

- name: >-
    18.10.8.2 | L1 |
    Ensure 'Set the default behavior for AutoRun' is set to 'Enabled: Do not execute any autorun commands'
  when:
    - w11cis_rule_18_10_8_2_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoAutorun
    data: 1
    type: dword
    state: present

- name: "18.10.8.3 | L1 | Ensure 'Turn off Autoplay' is set to 'Enabled: All drives'"
  when:
    - w11cis_rule_18_10_8_3_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoDriveTypeAutoRun
    data: 255
    type: dword
    state: present
