---
- name: "18.9.51.1.1 | L1 | Ensure 'Enable Windows NTP Client' is set to 'Enabled'"
  when:
    - w2019cis_rule_18_9_51_1_1_enabled
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\W32Time\TimeProviders\NtpClient
    name: Enabled
    data: 1
    type: dword
    state: present

- name: "18.9.51.1.2 | L1 | Ensure 'Enable Windows NTP Server' is set to 'Disabled' | MS only"
  when:
    - w2019cis_rule_18_9_51_1_2_enabled
    - _w2019cis_standalone_or_member_server
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\W32Time\TimeProviders\NtpServer
    name: Enabled
    data: 0
    type: dword
    state: present
