---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: l1dc
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level1
      - windows
      - windows_domain
      - windows_domain_controllers
  - name: l3dc
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level3
      - windows
      - windows_domain
      - windows_domain_controllers
  - name: l1ms
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level1
      - windows
      - windows_domain
      - windows_domain_members
  - name: l3ms
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level3
      - windows
      - windows_domain
      - windows_domain_members
  - name: l1standalone
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level1
      - windows
      - windows_standalone
  - name: l3standalone
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level3
      - windows
      - windows_standalone
  - name: l1template
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level1
      - windows
      - windows_standalone
      - windows_template
  - name: l3template
    box: jtarpley/w2025_base
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: cis_w2025_
    groups:
      - subjects
      - level3
      - windows
      - windows_standalone
      - windows_template
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        w2025cis_skip_reboot: false
        w2025cis_rule_9_3_4_enabled: false # Allow local firewall rules
        w2025cis_rule_9_3_5_enabled: false # Allow local connection security rules
        w2025cis_admin_username: localadmin
        w2025cis_guest_username: localguest
        w2025cis_login_message_text: |
            You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.

            By using this IS (which includes any device attached to this IS), you consent to the following conditions:

            -The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.

            -At any time, the USG may inspect and seize data stored on this IS.

            -Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.

            -This IS includes security measures (e.g., authentication and access controls) to protect USG interests--not for your personal benefit or privacy.

            -Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy, and their assistants. Such communications and work product are private and confidential. See User Agreement for details.

        w2025cis_login_message_title: DoD Notice and Consent Banner
      level1:
        w2025cis_level: 1
      level3:
        w2025cis_level: 3
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
        ansible_password: vagrant
      windows_domain_members:
        dc_inventory_name: l3dc
      windows_standalone:
        dc_inventory_name: l3dc
      windows_template:
        w2025cis_is_template: true
    host_vars:
      l1dc:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
        domain_name: test2.loc
        domain_base_dn: DC=test2,DC=loc
      l3dc:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
      l1ms:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
        ansible_user: TEST\vagrant
      l3ms:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
        ansible_user: TEST\vagrant
      l1standalone:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
      l3standalone:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
      l1template:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
      l3template:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
verifier:
  name: ansible
