---
- name: "5.1 | L1 | Ensure 'Print Spooler (Spooler)' is set to 'Disabled' | DC only"
  when:
    - w2025cis_rule_5_1_enabled
    - _w2025cis_domain_controller
  ansible.windows.win_service:
    name: Spooler
    start_mode: disabled
    state: stopped

- name: "5.2 | L2 | Ensure 'Print Spooler (Spooler)' is set to 'Disabled' | MS only"
  when:
    - w2025cis_rule_5_2_enabled
    - _w2025cis_standalone_or_member_server
    - w2025cis_rule_5_2_force or _w2025cis_level2
  ansible.windows.win_service:
    name: Spooler
    start_mode: disabled
    state: stopped
